# Private inputs (kept secret)
secret = "0x296461a41"
nullifier = "0x52c8c33fd"
path_indices = 
path_elements = 

# Public inputs (visible to everyone)
merkle_root = "0x245abe3e64bbfc8e6987a76b0c9e78bd48c10484c0b87b1a6a57c65cdbd0559f"
nullifier_hash = "0x142af85c7cb4836136bfa419438ff5d22be65c2316332dc50a37185772a64aa7"
recipient = "0xa2c372b2b354f15c656160834b41f3de1a8a7336"
relayer = "0x0"
fee = "0x0"
